import 'package:meta/meta.dart';

@immutable
final class CountryOption {
  const CountryOption({required this.name, required this.isoCode});

  final String name;
  final String isoCode;

  String get flagEmoji {
    final String normalized = isoCode.toUpperCase();
    return normalized.runes
        .map((int rune) => String.fromCharCode(rune + 127397))
        .join();
  }

  String get displayLabel => '$flagEmoji  $name';
  String get dialCode => _dialCodeByIso[isoCode] ?? '';

  static const CountryOption unitedStates = CountryOption(
    name: 'United States',
    isoCode: 'US',
  );

  static const CountryOption zimbabwe = CountryOption(
    name: 'Zimbabwe',
    isoCode: 'ZW',
  );

  static const List<CountryOption> all = <CountryOption>[
    CountryOption(name: 'Afghanistan', isoCode: 'AF'),
    CountryOption(name: 'Albania', isoCode: 'AL'),
    CountryOption(name: 'Algeria', isoCode: 'DZ'),
    CountryOption(name: 'Andorra', isoCode: 'AD'),
    CountryOption(name: 'Angola', isoCode: 'AO'),
    CountryOption(name: 'Antigua and Barbuda', isoCode: 'AG'),
    CountryOption(name: 'Argentina', isoCode: 'AR'),
    CountryOption(name: 'Armenia', isoCode: 'AM'),
    CountryOption(name: 'Australia', isoCode: 'AU'),
    CountryOption(name: 'Austria', isoCode: 'AT'),
    CountryOption(name: 'Azerbaijan', isoCode: 'AZ'),
    CountryOption(name: 'Bahamas', isoCode: 'BS'),
    CountryOption(name: 'Bahrain', isoCode: 'BH'),
    CountryOption(name: 'Bangladesh', isoCode: 'BD'),
    CountryOption(name: 'Barbados', isoCode: 'BB'),
    CountryOption(name: 'Belarus', isoCode: 'BY'),
    CountryOption(name: 'Belgium', isoCode: 'BE'),
    CountryOption(name: 'Belize', isoCode: 'BZ'),
    CountryOption(name: 'Benin', isoCode: 'BJ'),
    CountryOption(name: 'Bhutan', isoCode: 'BT'),
    CountryOption(name: 'Bolivia', isoCode: 'BO'),
    CountryOption(name: 'Bosnia and Herzegovina', isoCode: 'BA'),
    CountryOption(name: 'Botswana', isoCode: 'BW'),
    CountryOption(name: 'Brazil', isoCode: 'BR'),
    CountryOption(name: 'Brunei', isoCode: 'BN'),
    CountryOption(name: 'Bulgaria', isoCode: 'BG'),
    CountryOption(name: 'Burkina Faso', isoCode: 'BF'),
    CountryOption(name: 'Burundi', isoCode: 'BI'),
    CountryOption(name: 'Cambodia', isoCode: 'KH'),
    CountryOption(name: 'Cameroon', isoCode: 'CM'),
    CountryOption(name: 'Canada', isoCode: 'CA'),
    CountryOption(name: 'Cape Verde', isoCode: 'CV'),
    CountryOption(name: 'Central African Republic', isoCode: 'CF'),
    CountryOption(name: 'Chad', isoCode: 'TD'),
    CountryOption(name: 'Chile', isoCode: 'CL'),
    CountryOption(name: 'China', isoCode: 'CN'),
    CountryOption(name: 'Colombia', isoCode: 'CO'),
    CountryOption(name: 'Comoros', isoCode: 'KM'),
    CountryOption(name: 'Congo', isoCode: 'CG'),
    CountryOption(name: 'Costa Rica', isoCode: 'CR'),
    CountryOption(name: 'Croatia', isoCode: 'HR'),
    CountryOption(name: 'Cuba', isoCode: 'CU'),
    CountryOption(name: 'Cyprus', isoCode: 'CY'),
    CountryOption(name: 'Czech Republic', isoCode: 'CZ'),
    CountryOption(name: 'Denmark', isoCode: 'DK'),
    CountryOption(name: 'Djibouti', isoCode: 'DJ'),
    CountryOption(name: 'Dominica', isoCode: 'DM'),
    CountryOption(name: 'Dominican Republic', isoCode: 'DO'),
    CountryOption(name: 'Ecuador', isoCode: 'EC'),
    CountryOption(name: 'Egypt', isoCode: 'EG'),
    CountryOption(name: 'El Salvador', isoCode: 'SV'),
    CountryOption(name: 'Equatorial Guinea', isoCode: 'GQ'),
    CountryOption(name: 'Eritrea', isoCode: 'ER'),
    CountryOption(name: 'Estonia', isoCode: 'EE'),
    CountryOption(name: 'Eswatini', isoCode: 'SZ'),
    CountryOption(name: 'Ethiopia', isoCode: 'ET'),
    CountryOption(name: 'Fiji', isoCode: 'FJ'),
    CountryOption(name: 'Finland', isoCode: 'FI'),
    CountryOption(name: 'France', isoCode: 'FR'),
    CountryOption(name: 'Gabon', isoCode: 'GA'),
    CountryOption(name: 'Gambia', isoCode: 'GM'),
    CountryOption(name: 'Georgia', isoCode: 'GE'),
    CountryOption(name: 'Germany', isoCode: 'DE'),
    CountryOption(name: 'Ghana', isoCode: 'GH'),
    CountryOption(name: 'Greece', isoCode: 'GR'),
    CountryOption(name: 'Grenada', isoCode: 'GD'),
    CountryOption(name: 'Guatemala', isoCode: 'GT'),
    CountryOption(name: 'Guinea', isoCode: 'GN'),
    CountryOption(name: 'Guinea-Bissau', isoCode: 'GW'),
    CountryOption(name: 'Guyana', isoCode: 'GY'),
    CountryOption(name: 'Haiti', isoCode: 'HT'),
    CountryOption(name: 'Honduras', isoCode: 'HN'),
    CountryOption(name: 'Hungary', isoCode: 'HU'),
    CountryOption(name: 'Iceland', isoCode: 'IS'),
    CountryOption(name: 'India', isoCode: 'IN'),
    CountryOption(name: 'Indonesia', isoCode: 'ID'),
    CountryOption(name: 'Iran', isoCode: 'IR'),
    CountryOption(name: 'Iraq', isoCode: 'IQ'),
    CountryOption(name: 'Ireland', isoCode: 'IE'),
    CountryOption(name: 'Israel', isoCode: 'IL'),
    CountryOption(name: 'Italy', isoCode: 'IT'),
    CountryOption(name: 'Jamaica', isoCode: 'JM'),
    CountryOption(name: 'Japan', isoCode: 'JP'),
    CountryOption(name: 'Jordan', isoCode: 'JO'),
    CountryOption(name: 'Kazakhstan', isoCode: 'KZ'),
    CountryOption(name: 'Kenya', isoCode: 'KE'),
    CountryOption(name: 'Kiribati', isoCode: 'KI'),
    CountryOption(name: 'Kuwait', isoCode: 'KW'),
    CountryOption(name: 'Kyrgyzstan', isoCode: 'KG'),
    CountryOption(name: 'Laos', isoCode: 'LA'),
    CountryOption(name: 'Latvia', isoCode: 'LV'),
    CountryOption(name: 'Lebanon', isoCode: 'LB'),
    CountryOption(name: 'Lesotho', isoCode: 'LS'),
    CountryOption(name: 'Liberia', isoCode: 'LR'),
    CountryOption(name: 'Libya', isoCode: 'LY'),
    CountryOption(name: 'Liechtenstein', isoCode: 'LI'),
    CountryOption(name: 'Lithuania', isoCode: 'LT'),
    CountryOption(name: 'Luxembourg', isoCode: 'LU'),
    CountryOption(name: 'Madagascar', isoCode: 'MG'),
    CountryOption(name: 'Malawi', isoCode: 'MW'),
    CountryOption(name: 'Malaysia', isoCode: 'MY'),
    CountryOption(name: 'Maldives', isoCode: 'MV'),
    CountryOption(name: 'Mali', isoCode: 'ML'),
    CountryOption(name: 'Malta', isoCode: 'MT'),
    CountryOption(name: 'Marshall Islands', isoCode: 'MH'),
    CountryOption(name: 'Mauritania', isoCode: 'MR'),
    CountryOption(name: 'Mauritius', isoCode: 'MU'),
    CountryOption(name: 'Mexico', isoCode: 'MX'),
    CountryOption(name: 'Micronesia', isoCode: 'FM'),
    CountryOption(name: 'Moldova', isoCode: 'MD'),
    CountryOption(name: 'Monaco', isoCode: 'MC'),
    CountryOption(name: 'Mongolia', isoCode: 'MN'),
    CountryOption(name: 'Montenegro', isoCode: 'ME'),
    CountryOption(name: 'Morocco', isoCode: 'MA'),
    CountryOption(name: 'Mozambique', isoCode: 'MZ'),
    CountryOption(name: 'Myanmar', isoCode: 'MM'),
    CountryOption(name: 'Namibia', isoCode: 'NA'),
    CountryOption(name: 'Nauru', isoCode: 'NR'),
    CountryOption(name: 'Nepal', isoCode: 'NP'),
    CountryOption(name: 'Netherlands', isoCode: 'NL'),
    CountryOption(name: 'New Zealand', isoCode: 'NZ'),
    CountryOption(name: 'Nicaragua', isoCode: 'NI'),
    CountryOption(name: 'Niger', isoCode: 'NE'),
    CountryOption(name: 'Nigeria', isoCode: 'NG'),
    CountryOption(name: 'North Korea', isoCode: 'KP'),
    CountryOption(name: 'North Macedonia', isoCode: 'MK'),
    CountryOption(name: 'Norway', isoCode: 'NO'),
    CountryOption(name: 'Oman', isoCode: 'OM'),
    CountryOption(name: 'Pakistan', isoCode: 'PK'),
    CountryOption(name: 'Palau', isoCode: 'PW'),
    CountryOption(name: 'Panama', isoCode: 'PA'),
    CountryOption(name: 'Papua New Guinea', isoCode: 'PG'),
    CountryOption(name: 'Paraguay', isoCode: 'PY'),
    CountryOption(name: 'Peru', isoCode: 'PE'),
    CountryOption(name: 'Philippines', isoCode: 'PH'),
    CountryOption(name: 'Poland', isoCode: 'PL'),
    CountryOption(name: 'Portugal', isoCode: 'PT'),
    CountryOption(name: 'Qatar', isoCode: 'QA'),
    CountryOption(name: 'Romania', isoCode: 'RO'),
    CountryOption(name: 'Russia', isoCode: 'RU'),
    CountryOption(name: 'Rwanda', isoCode: 'RW'),
    CountryOption(name: 'Saint Kitts and Nevis', isoCode: 'KN'),
    CountryOption(name: 'Saint Lucia', isoCode: 'LC'),
    CountryOption(name: 'Saint Vincent and the Grenadines', isoCode: 'VC'),
    CountryOption(name: 'Samoa', isoCode: 'WS'),
    CountryOption(name: 'San Marino', isoCode: 'SM'),
    CountryOption(name: 'Sao Tome and Principe', isoCode: 'ST'),
    CountryOption(name: 'Saudi Arabia', isoCode: 'SA'),
    CountryOption(name: 'Senegal', isoCode: 'SN'),
    CountryOption(name: 'Serbia', isoCode: 'RS'),
    CountryOption(name: 'Seychelles', isoCode: 'SC'),
    CountryOption(name: 'Sierra Leone', isoCode: 'SL'),
    CountryOption(name: 'Singapore', isoCode: 'SG'),
    CountryOption(name: 'Slovakia', isoCode: 'SK'),
    CountryOption(name: 'Slovenia', isoCode: 'SI'),
    CountryOption(name: 'Solomon Islands', isoCode: 'SB'),
    CountryOption(name: 'Somalia', isoCode: 'SO'),
    CountryOption(name: 'South Africa', isoCode: 'ZA'),
    CountryOption(name: 'South Korea', isoCode: 'KR'),
    CountryOption(name: 'South Sudan', isoCode: 'SS'),
    CountryOption(name: 'Spain', isoCode: 'ES'),
    CountryOption(name: 'Sri Lanka', isoCode: 'LK'),
    CountryOption(name: 'Sudan', isoCode: 'SD'),
    CountryOption(name: 'Suriname', isoCode: 'SR'),
    CountryOption(name: 'Sweden', isoCode: 'SE'),
    CountryOption(name: 'Switzerland', isoCode: 'CH'),
    CountryOption(name: 'Syria', isoCode: 'SY'),
    CountryOption(name: 'Taiwan', isoCode: 'TW'),
    CountryOption(name: 'Tajikistan', isoCode: 'TJ'),
    CountryOption(name: 'Tanzania', isoCode: 'TZ'),
    CountryOption(name: 'Thailand', isoCode: 'TH'),
    CountryOption(name: 'Timor-Leste', isoCode: 'TL'),
    CountryOption(name: 'Togo', isoCode: 'TG'),
    CountryOption(name: 'Tonga', isoCode: 'TO'),
    CountryOption(name: 'Trinidad and Tobago', isoCode: 'TT'),
    CountryOption(name: 'Tunisia', isoCode: 'TN'),
    CountryOption(name: 'Turkey', isoCode: 'TR'),
    CountryOption(name: 'Turkmenistan', isoCode: 'TM'),
    CountryOption(name: 'Tuvalu', isoCode: 'TV'),
    CountryOption(name: 'Uganda', isoCode: 'UG'),
    CountryOption(name: 'Ukraine', isoCode: 'UA'),
    CountryOption(name: 'United Arab Emirates', isoCode: 'AE'),
    unitedStates,
    CountryOption(name: 'United Kingdom', isoCode: 'GB'),
    CountryOption(name: 'Uruguay', isoCode: 'UY'),
    CountryOption(name: 'Uzbekistan', isoCode: 'UZ'),
    CountryOption(name: 'Vanuatu', isoCode: 'VU'),
    CountryOption(name: 'Vatican City', isoCode: 'VA'),
    CountryOption(name: 'Venezuela', isoCode: 'VE'),
    CountryOption(name: 'Vietnam', isoCode: 'VN'),
    CountryOption(name: 'Yemen', isoCode: 'YE'),
    CountryOption(name: 'Zambia', isoCode: 'ZM'),
    zimbabwe,
  ];

  static const Map<String, String> _dialCodeByIso = <String, String>{
    'AE': '+971',
    'AF': '+93',
    'AG': '+1',
    'AL': '+355',
    'AM': '+374',
    'AO': '+244',
    'AR': '+54',
    'AT': '+43',
    'AU': '+61',
    'AZ': '+994',
    'BA': '+387',
    'BB': '+1',
    'BD': '+880',
    'BE': '+32',
    'BF': '+226',
    'BG': '+359',
    'BH': '+973',
    'BI': '+257',
    'BJ': '+229',
    'BN': '+673',
    'BO': '+591',
    'BR': '+55',
    'BS': '+1',
    'BT': '+975',
    'BW': '+267',
    'BY': '+375',
    'BZ': '+501',
    'CA': '+1',
    'CD': '+243',
    'CF': '+236',
    'CG': '+242',
    'CH': '+41',
    'CI': '+225',
    'CL': '+56',
    'CM': '+237',
    'CN': '+86',
    'CO': '+57',
    'CR': '+506',
    'CU': '+53',
    'CV': '+238',
    'CY': '+357',
    'CZ': '+420',
    'DE': '+49',
    'DJ': '+253',
    'DK': '+45',
    'DM': '+1',
    'DO': '+1',
    'DZ': '+213',
    'EC': '+593',
    'EE': '+372',
    'EG': '+20',
    'ER': '+291',
    'ES': '+34',
    'ET': '+251',
    'FI': '+358',
    'FJ': '+679',
    'FM': '+691',
    'FR': '+33',
    'GA': '+241',
    'GB': '+44',
    'GD': '+1',
    'GE': '+995',
    'GH': '+233',
    'GM': '+220',
    'GN': '+224',
    'GQ': '+240',
    'GR': '+30',
    'GT': '+502',
    'GW': '+245',
    'GY': '+592',
    'HN': '+504',
    'HR': '+385',
    'HT': '+509',
    'HU': '+36',
    'ID': '+62',
    'IE': '+353',
    'IL': '+972',
    'IN': '+91',
    'IQ': '+964',
    'IR': '+98',
    'IS': '+354',
    'IT': '+39',
    'JM': '+1',
    'JO': '+962',
    'JP': '+81',
    'KE': '+254',
    'KG': '+996',
    'KH': '+855',
    'KI': '+686',
    'KM': '+269',
    'KN': '+1',
    'KP': '+850',
    'KR': '+82',
    'KW': '+965',
    'KZ': '+7',
    'LA': '+856',
    'LB': '+961',
    'LC': '+1',
    'LI': '+423',
    'LK': '+94',
    'LR': '+231',
    'LS': '+266',
    'LT': '+370',
    'LU': '+352',
    'LV': '+371',
    'LY': '+218',
    'MA': '+212',
    'MC': '+377',
    'MD': '+373',
    'ME': '+382',
    'MG': '+261',
    'MH': '+692',
    'MK': '+389',
    'ML': '+223',
    'MM': '+95',
    'MN': '+976',
    'MR': '+222',
    'MT': '+356',
    'MU': '+230',
    'MV': '+960',
    'MW': '+265',
    'MX': '+52',
    'MY': '+60',
    'MZ': '+258',
    'NA': '+264',
    'NE': '+227',
    'NG': '+234',
    'NI': '+505',
    'NL': '+31',
    'NO': '+47',
    'NP': '+977',
    'NR': '+674',
    'NZ': '+64',
    'OM': '+968',
    'PA': '+507',
    'PE': '+51',
    'PG': '+675',
    'PH': '+63',
    'PK': '+92',
    'PL': '+48',
    'PT': '+351',
    'PW': '+680',
    'PY': '+595',
    'QA': '+974',
    'RO': '+40',
    'RS': '+381',
    'RU': '+7',
    'RW': '+250',
    'SA': '+966',
    'SB': '+677',
    'SC': '+248',
    'SD': '+249',
    'SE': '+46',
    'SG': '+65',
    'SI': '+386',
    'SK': '+421',
    'SL': '+232',
    'SM': '+378',
    'SN': '+221',
    'SO': '+252',
    'SR': '+597',
    'SS': '+211',
    'ST': '+239',
    'SV': '+503',
    'SY': '+963',
    'SZ': '+268',
    'TD': '+235',
    'TG': '+228',
    'TH': '+66',
    'TJ': '+992',
    'TL': '+670',
    'TM': '+993',
    'TN': '+216',
    'TO': '+676',
    'TR': '+90',
    'TT': '+1',
    'TV': '+688',
    'TW': '+886',
    'TZ': '+255',
    'UA': '+380',
    'UG': '+256',
    'US': '+1',
    'UY': '+598',
    'UZ': '+998',
    'VA': '+379',
    'VC': '+1',
    'VE': '+58',
    'VN': '+84',
    'VU': '+678',
    'WS': '+685',
    'YE': '+967',
    'ZA': '+27',
    'ZM': '+260',
    'ZW': '+263',
  };
}
